{
 "title": "Redis Dashboard",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "used, {{ instance }}"
    },
    {
     "expr": "redis_memory_max_bytes{instance=~\"$instance\"}",
     "legendFormat": "max, {{ instance }}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "hits, {{ instance }}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "misses, {{ instance }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) by (db, instance)",
     "legendFormat": "{{ db }}, {{ instance }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) by (instance) - sum (redis_db_keys_expiring{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "not expiring, {{ instance }}"
    },
    {
     "expr": "sum (redis_db_keys_expiring{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "expiring, {{ instance }}"
    }
   ]
  },
  {
   "title": "Expired/Evicted Keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "expired, {{ instance }}"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "evicted, {{ instance }}"
    }
   ]
  },
  {
   "title": "Connected/Blocked Clients",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{instance=~\"$instance\"})",
     "legendFormat": "connected"
    },
    {
     "expr": "sum(redis_blocked_clients{instance=~\"$instance\"})",
     "legendFormat": "blocked"
    }
   ]
  }
 ]
}