global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alerts/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ "alertmanager:9093" ]

scrape_configs:
  - job_name: node_exporter
    static_configs:
      - targets: [ "node_exporter:9100" ]

  - job_name: api
    static_configs:
      - targets: [ "api:8000" ]

  - job_name: loki
    static_configs:
      - targets: [ "loki:3100" ]

  - job_name: alertmanager
    static_configs:
      - targets: [ "alertmanager:9093" ]
