version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    command: [ "uvicorn", "--workers", "10", "api.app:app", "--host", "0.0.0.0", "--port", "8000" ]
    env_file:
      - ./config/.env
    environment:
      - DB_HOST=mysql
      - AMQP_HOST=rabbitmq
    ports:
      - "8000:8000"

  scanner:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    command: [ "python3", "scanner/app.py" ]
    env_file:
      - ./config/.env
    environment:
      - DB_HOST=mysql
      - AMQP_HOST=rabbitmq

  mysql:
    image: mysql
    env_file:
      - ./config/.env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 3s
      retries: 100
    volumes:
      - ./data/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    env_file:
      - ./config/.env
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      timeout: 3s
      retries: 100
    ports:
      - "15672:15672"
