name: lab4

services:
  api:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    command: [ "uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000" ]
    env_file:
      - ./config/.env
    environment:
      - DB_HOST=mysql
      - AMQP_HOST=rabbitmq
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  scanner:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    command: [ "python3", "scanner/app.py" ]
    env_file:
      - ./config/.env
    environment:
      - DB_HOST=mysql
      - AMQP_HOST=rabbitmq
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  mysql:
    image: mysql
    env_file:
      - ./config/.env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 3s
      retries: 100
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:management
    env_file:
      - ./config/.env
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      timeout: 3s
      retries: 100
    ports:
      - "15672:15672"
      - "5672:5672"
