version: '3.8'

services:
  mysql:
    image: mysql
    env_file:
      - config/.env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 3s
      retries: 100
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:management
    env_file:
      - config/.env
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      timeout: 3s
      retries: 100
    ports:
      - "5672:5672"
      - "15672:15672"
